//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/InputSystemAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputSystemAction.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""InputSystemAction"",
    ""maps"": [
        {
            ""name"": ""Explore"",
            ""id"": ""486db36a-b1a5-4a7e-a742-0e3708fd1cd1"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""d04a9e83-7882-4517-9df3-a17e6be92a8f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""6ab72d70-df8b-4956-aaa0-b2918a841a0d"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateCam"",
                    ""type"": ""Value"",
                    ""id"": ""e5186efa-6fcb-459e-a5e2-203b506845bc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""OpenInventory"",
                    ""type"": ""Button"",
                    ""id"": ""e71aa535-c3cb-4b02-a259-fd226ff33af0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchHoldItem"",
                    ""type"": ""Value"",
                    ""id"": ""5bcb91e0-9a42-4786-8208-cfa7babdcec6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""89de925c-2913-4975-8a3e-8d4d458f68f5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""016dde01-6181-4abd-a349-9ae5354d450a"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""8cabc876-9e25-4ea0-aa37-f75443b3c3b9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""76a7bb01-385c-4f24-a7ee-cd4aba9ae77a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""759afa69-7c55-44b9-8c0d-5f23420966ca"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""537dcbd3-de5f-4a47-902f-168696fd7f4a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7c39559-cbd4-41fa-9c07-07ebdef21781"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82059720-50e7-418b-9c6f-77ad99d3425a"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0cc4b675-a729-4f97-96fe-272246b60e35"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchHoldItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OpenInventory"",
            ""id"": ""2c2d7874-b9e2-49e3-9a5e-ffa5f1db128a"",
            ""actions"": [
                {
                    ""name"": ""RotateItemInventory"",
                    ""type"": ""Value"",
                    ""id"": ""fe7c3edb-f7f5-4f63-88ae-1b610ab08311"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CloseInventory"",
                    ""type"": ""Button"",
                    ""id"": ""7fa44528-ca5e-4397-b322-5ac52e460a1a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""045a0bc4-a227-4349-b811-f353012ab907"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateItemInventory"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9088ae39-10fe-44ec-b0ce-ed7badac0084"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateItemInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e4d6271c-bfe7-424f-aef1-c41679dc5927"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateItemInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2387bf84-03d7-48d4-8181-4ed6ff04b6b5"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Conversation"",
            ""id"": ""adfc1e02-60d5-4191-977b-95538b773f10"",
            ""actions"": [
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""a82c9ec1-25d8-46da-a33f-50cbc6ddb5ef"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d6974098-4b3a-4f50-a3f7-f2e6a00f5bef"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ReadingDocument"",
            ""id"": ""56a0905c-8073-4dc2-9df4-9a11e08d092b"",
            ""actions"": [
                {
                    ""name"": ""CloseReading"",
                    ""type"": ""Button"",
                    ""id"": ""7a848b35-208d-4df4-9457-2e297d45e6b6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f9d2f81b-6114-452d-8beb-32fc29d57225"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseReading"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Explore
        m_Explore = asset.FindActionMap("Explore", throwIfNotFound: true);
        m_Explore_Move = m_Explore.FindAction("Move", throwIfNotFound: true);
        m_Explore_Interact = m_Explore.FindAction("Interact", throwIfNotFound: true);
        m_Explore_RotateCam = m_Explore.FindAction("RotateCam", throwIfNotFound: true);
        m_Explore_OpenInventory = m_Explore.FindAction("OpenInventory", throwIfNotFound: true);
        m_Explore_SwitchHoldItem = m_Explore.FindAction("SwitchHoldItem", throwIfNotFound: true);
        // OpenInventory
        m_OpenInventory = asset.FindActionMap("OpenInventory", throwIfNotFound: true);
        m_OpenInventory_RotateItemInventory = m_OpenInventory.FindAction("RotateItemInventory", throwIfNotFound: true);
        m_OpenInventory_CloseInventory = m_OpenInventory.FindAction("CloseInventory", throwIfNotFound: true);
        // Conversation
        m_Conversation = asset.FindActionMap("Conversation", throwIfNotFound: true);
        m_Conversation_Interaction = m_Conversation.FindAction("Interaction", throwIfNotFound: true);
        // ReadingDocument
        m_ReadingDocument = asset.FindActionMap("ReadingDocument", throwIfNotFound: true);
        m_ReadingDocument_CloseReading = m_ReadingDocument.FindAction("CloseReading", throwIfNotFound: true);
    }

    ~@PlayerInput()
    {
        UnityEngine.Debug.Assert(!m_Explore.enabled, "This will cause a leak and performance issues, PlayerInput.Explore.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_OpenInventory.enabled, "This will cause a leak and performance issues, PlayerInput.OpenInventory.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Conversation.enabled, "This will cause a leak and performance issues, PlayerInput.Conversation.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_ReadingDocument.enabled, "This will cause a leak and performance issues, PlayerInput.ReadingDocument.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Explore
    private readonly InputActionMap m_Explore;
    private List<IExploreActions> m_ExploreActionsCallbackInterfaces = new List<IExploreActions>();
    private readonly InputAction m_Explore_Move;
    private readonly InputAction m_Explore_Interact;
    private readonly InputAction m_Explore_RotateCam;
    private readonly InputAction m_Explore_OpenInventory;
    private readonly InputAction m_Explore_SwitchHoldItem;
    /// <summary>
    /// Provides access to input actions defined in input action map "Explore".
    /// </summary>
    public struct ExploreActions
    {
        private @PlayerInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ExploreActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Explore/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_Explore_Move;
        /// <summary>
        /// Provides access to the underlying input action "Explore/Interact".
        /// </summary>
        public InputAction @Interact => m_Wrapper.m_Explore_Interact;
        /// <summary>
        /// Provides access to the underlying input action "Explore/RotateCam".
        /// </summary>
        public InputAction @RotateCam => m_Wrapper.m_Explore_RotateCam;
        /// <summary>
        /// Provides access to the underlying input action "Explore/OpenInventory".
        /// </summary>
        public InputAction @OpenInventory => m_Wrapper.m_Explore_OpenInventory;
        /// <summary>
        /// Provides access to the underlying input action "Explore/SwitchHoldItem".
        /// </summary>
        public InputAction @SwitchHoldItem => m_Wrapper.m_Explore_SwitchHoldItem;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Explore; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ExploreActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ExploreActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ExploreActions" />
        public void AddCallbacks(IExploreActions instance)
        {
            if (instance == null || m_Wrapper.m_ExploreActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ExploreActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @RotateCam.started += instance.OnRotateCam;
            @RotateCam.performed += instance.OnRotateCam;
            @RotateCam.canceled += instance.OnRotateCam;
            @OpenInventory.started += instance.OnOpenInventory;
            @OpenInventory.performed += instance.OnOpenInventory;
            @OpenInventory.canceled += instance.OnOpenInventory;
            @SwitchHoldItem.started += instance.OnSwitchHoldItem;
            @SwitchHoldItem.performed += instance.OnSwitchHoldItem;
            @SwitchHoldItem.canceled += instance.OnSwitchHoldItem;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ExploreActions" />
        private void UnregisterCallbacks(IExploreActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @RotateCam.started -= instance.OnRotateCam;
            @RotateCam.performed -= instance.OnRotateCam;
            @RotateCam.canceled -= instance.OnRotateCam;
            @OpenInventory.started -= instance.OnOpenInventory;
            @OpenInventory.performed -= instance.OnOpenInventory;
            @OpenInventory.canceled -= instance.OnOpenInventory;
            @SwitchHoldItem.started -= instance.OnSwitchHoldItem;
            @SwitchHoldItem.performed -= instance.OnSwitchHoldItem;
            @SwitchHoldItem.canceled -= instance.OnSwitchHoldItem;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ExploreActions.UnregisterCallbacks(IExploreActions)" />.
        /// </summary>
        /// <seealso cref="ExploreActions.UnregisterCallbacks(IExploreActions)" />
        public void RemoveCallbacks(IExploreActions instance)
        {
            if (m_Wrapper.m_ExploreActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ExploreActions.AddCallbacks(IExploreActions)" />
        /// <seealso cref="ExploreActions.RemoveCallbacks(IExploreActions)" />
        /// <seealso cref="ExploreActions.UnregisterCallbacks(IExploreActions)" />
        public void SetCallbacks(IExploreActions instance)
        {
            foreach (var item in m_Wrapper.m_ExploreActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ExploreActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ExploreActions" /> instance referencing this action map.
    /// </summary>
    public ExploreActions @Explore => new ExploreActions(this);

    // OpenInventory
    private readonly InputActionMap m_OpenInventory;
    private List<IOpenInventoryActions> m_OpenInventoryActionsCallbackInterfaces = new List<IOpenInventoryActions>();
    private readonly InputAction m_OpenInventory_RotateItemInventory;
    private readonly InputAction m_OpenInventory_CloseInventory;
    /// <summary>
    /// Provides access to input actions defined in input action map "OpenInventory".
    /// </summary>
    public struct OpenInventoryActions
    {
        private @PlayerInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public OpenInventoryActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "OpenInventory/RotateItemInventory".
        /// </summary>
        public InputAction @RotateItemInventory => m_Wrapper.m_OpenInventory_RotateItemInventory;
        /// <summary>
        /// Provides access to the underlying input action "OpenInventory/CloseInventory".
        /// </summary>
        public InputAction @CloseInventory => m_Wrapper.m_OpenInventory_CloseInventory;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_OpenInventory; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="OpenInventoryActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(OpenInventoryActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="OpenInventoryActions" />
        public void AddCallbacks(IOpenInventoryActions instance)
        {
            if (instance == null || m_Wrapper.m_OpenInventoryActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_OpenInventoryActionsCallbackInterfaces.Add(instance);
            @RotateItemInventory.started += instance.OnRotateItemInventory;
            @RotateItemInventory.performed += instance.OnRotateItemInventory;
            @RotateItemInventory.canceled += instance.OnRotateItemInventory;
            @CloseInventory.started += instance.OnCloseInventory;
            @CloseInventory.performed += instance.OnCloseInventory;
            @CloseInventory.canceled += instance.OnCloseInventory;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="OpenInventoryActions" />
        private void UnregisterCallbacks(IOpenInventoryActions instance)
        {
            @RotateItemInventory.started -= instance.OnRotateItemInventory;
            @RotateItemInventory.performed -= instance.OnRotateItemInventory;
            @RotateItemInventory.canceled -= instance.OnRotateItemInventory;
            @CloseInventory.started -= instance.OnCloseInventory;
            @CloseInventory.performed -= instance.OnCloseInventory;
            @CloseInventory.canceled -= instance.OnCloseInventory;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="OpenInventoryActions.UnregisterCallbacks(IOpenInventoryActions)" />.
        /// </summary>
        /// <seealso cref="OpenInventoryActions.UnregisterCallbacks(IOpenInventoryActions)" />
        public void RemoveCallbacks(IOpenInventoryActions instance)
        {
            if (m_Wrapper.m_OpenInventoryActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="OpenInventoryActions.AddCallbacks(IOpenInventoryActions)" />
        /// <seealso cref="OpenInventoryActions.RemoveCallbacks(IOpenInventoryActions)" />
        /// <seealso cref="OpenInventoryActions.UnregisterCallbacks(IOpenInventoryActions)" />
        public void SetCallbacks(IOpenInventoryActions instance)
        {
            foreach (var item in m_Wrapper.m_OpenInventoryActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_OpenInventoryActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="OpenInventoryActions" /> instance referencing this action map.
    /// </summary>
    public OpenInventoryActions @OpenInventory => new OpenInventoryActions(this);

    // Conversation
    private readonly InputActionMap m_Conversation;
    private List<IConversationActions> m_ConversationActionsCallbackInterfaces = new List<IConversationActions>();
    private readonly InputAction m_Conversation_Interaction;
    /// <summary>
    /// Provides access to input actions defined in input action map "Conversation".
    /// </summary>
    public struct ConversationActions
    {
        private @PlayerInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ConversationActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Conversation/Interaction".
        /// </summary>
        public InputAction @Interaction => m_Wrapper.m_Conversation_Interaction;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Conversation; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ConversationActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ConversationActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ConversationActions" />
        public void AddCallbacks(IConversationActions instance)
        {
            if (instance == null || m_Wrapper.m_ConversationActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ConversationActionsCallbackInterfaces.Add(instance);
            @Interaction.started += instance.OnInteraction;
            @Interaction.performed += instance.OnInteraction;
            @Interaction.canceled += instance.OnInteraction;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ConversationActions" />
        private void UnregisterCallbacks(IConversationActions instance)
        {
            @Interaction.started -= instance.OnInteraction;
            @Interaction.performed -= instance.OnInteraction;
            @Interaction.canceled -= instance.OnInteraction;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ConversationActions.UnregisterCallbacks(IConversationActions)" />.
        /// </summary>
        /// <seealso cref="ConversationActions.UnregisterCallbacks(IConversationActions)" />
        public void RemoveCallbacks(IConversationActions instance)
        {
            if (m_Wrapper.m_ConversationActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ConversationActions.AddCallbacks(IConversationActions)" />
        /// <seealso cref="ConversationActions.RemoveCallbacks(IConversationActions)" />
        /// <seealso cref="ConversationActions.UnregisterCallbacks(IConversationActions)" />
        public void SetCallbacks(IConversationActions instance)
        {
            foreach (var item in m_Wrapper.m_ConversationActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ConversationActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ConversationActions" /> instance referencing this action map.
    /// </summary>
    public ConversationActions @Conversation => new ConversationActions(this);

    // ReadingDocument
    private readonly InputActionMap m_ReadingDocument;
    private List<IReadingDocumentActions> m_ReadingDocumentActionsCallbackInterfaces = new List<IReadingDocumentActions>();
    private readonly InputAction m_ReadingDocument_CloseReading;
    /// <summary>
    /// Provides access to input actions defined in input action map "ReadingDocument".
    /// </summary>
    public struct ReadingDocumentActions
    {
        private @PlayerInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public ReadingDocumentActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "ReadingDocument/CloseReading".
        /// </summary>
        public InputAction @CloseReading => m_Wrapper.m_ReadingDocument_CloseReading;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_ReadingDocument; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="ReadingDocumentActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(ReadingDocumentActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="ReadingDocumentActions" />
        public void AddCallbacks(IReadingDocumentActions instance)
        {
            if (instance == null || m_Wrapper.m_ReadingDocumentActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ReadingDocumentActionsCallbackInterfaces.Add(instance);
            @CloseReading.started += instance.OnCloseReading;
            @CloseReading.performed += instance.OnCloseReading;
            @CloseReading.canceled += instance.OnCloseReading;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="ReadingDocumentActions" />
        private void UnregisterCallbacks(IReadingDocumentActions instance)
        {
            @CloseReading.started -= instance.OnCloseReading;
            @CloseReading.performed -= instance.OnCloseReading;
            @CloseReading.canceled -= instance.OnCloseReading;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="ReadingDocumentActions.UnregisterCallbacks(IReadingDocumentActions)" />.
        /// </summary>
        /// <seealso cref="ReadingDocumentActions.UnregisterCallbacks(IReadingDocumentActions)" />
        public void RemoveCallbacks(IReadingDocumentActions instance)
        {
            if (m_Wrapper.m_ReadingDocumentActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="ReadingDocumentActions.AddCallbacks(IReadingDocumentActions)" />
        /// <seealso cref="ReadingDocumentActions.RemoveCallbacks(IReadingDocumentActions)" />
        /// <seealso cref="ReadingDocumentActions.UnregisterCallbacks(IReadingDocumentActions)" />
        public void SetCallbacks(IReadingDocumentActions instance)
        {
            foreach (var item in m_Wrapper.m_ReadingDocumentActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ReadingDocumentActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="ReadingDocumentActions" /> instance referencing this action map.
    /// </summary>
    public ReadingDocumentActions @ReadingDocument => new ReadingDocumentActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Explore" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ExploreActions.AddCallbacks(IExploreActions)" />
    /// <seealso cref="ExploreActions.RemoveCallbacks(IExploreActions)" />
    public interface IExploreActions
    {
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Interact" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnInteract(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RotateCam" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotateCam(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "OpenInventory" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnOpenInventory(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SwitchHoldItem" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSwitchHoldItem(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "OpenInventory" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="OpenInventoryActions.AddCallbacks(IOpenInventoryActions)" />
    /// <seealso cref="OpenInventoryActions.RemoveCallbacks(IOpenInventoryActions)" />
    public interface IOpenInventoryActions
    {
        /// <summary>
        /// Method invoked when associated input action "RotateItemInventory" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotateItemInventory(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "CloseInventory" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCloseInventory(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Conversation" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ConversationActions.AddCallbacks(IConversationActions)" />
    /// <seealso cref="ConversationActions.RemoveCallbacks(IConversationActions)" />
    public interface IConversationActions
    {
        /// <summary>
        /// Method invoked when associated input action "Interaction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnInteraction(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "ReadingDocument" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="ReadingDocumentActions.AddCallbacks(IReadingDocumentActions)" />
    /// <seealso cref="ReadingDocumentActions.RemoveCallbacks(IReadingDocumentActions)" />
    public interface IReadingDocumentActions
    {
        /// <summary>
        /// Method invoked when associated input action "CloseReading" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCloseReading(InputAction.CallbackContext context);
    }
}
